### ISSUE TITLE
Don't implement TODO multi-nsqd support

### ISSUE THREAD

**Issue by discordianfish** [lovoo/nsq_exporter#4]
Hi,

I'm looking for a nsqd exporter and came across this project. Awesome!
For now, I just want to say I would recommend to run one exporter instance per nsqd instance and not implement discovery via nsqlookupd because it make it easier to isolate failures to specific instances and leave the instance labeling to prometheus. This is generally considered best practice in the prometheus community.

**Comment by 0x46616c6b** [comment]
Yes, you're right. We provide in our production setup on every nsqd node an exporter as well. I will remove it from the TODO. Good point!

**Comment by 0x46616c6b** [comment]
Removed #5
